# Runs all the tests written in the test folder.

# get a flutter container
container:
  image: ghcr.io/cirruslabs/flutter:3.16.4


# Analyzes and Lints the dart code according to analysis_options.yml
analyze_task:
  name: Analyze and Lint
  install_script: dart pub get
  format_script: dart format .
  analyze_script: dart analyze --fatal-infos

pr_test_task:
  name: Running Local Tests
  only_if: $CIRRUS_PR != ''
  depends_on:
    - Analyze and Lint
    - Installing LCOV
  pub_cache:
    folder: ~/.pub-cache
#  runs ```flutter pub get ``` before running the tests in the test/ folder
#  runs additional null assertions on the boundaries of migrated and un-migrated code.
  install_lcov: sudo apt-get install -y lcov
  test_script: flutter test --pub --null-assertions --coverage=./test/coverage/report/

test_task:
  name: LAST CHECKPOINT
  only_if: $CIRRUS_BRANCH == 'production' 
  depends_on:
    - Analyze and Lint
  pub_cache:
    folder: ~/.pub-cache
#  runs ```flutter pub get ``` before running the tests in the test/ folder
#  runs additional null assertions on the boundaries of migrated and un-migrated code.
  test_script: flutter test --null-assertions
